# 🐾 Generated by Wooper for server constants 🐾


# 💦☁────────────────────────────────────────────💦☁
#       STRAYMONS__TEXT_CHANNELS
# 💦☁────────────────────────────────────────────💦☁
class STRAYMONS__TEXT_CHANNELS:

    # 🌊💙🤍───────────── _Ai_Systems ─────────────💙🤍🌊
    error_logs = 1410202143570530375
    server_logs = 1182270234636320798
    role_logs = 1320577239334518854
    message_logs = 1137172628096958596
    bot_logs = 1400998689018875904
    ga_transcripts = 1297236581425352745
    community_updates = 1047856021982425232
    prize_transcripts = 1297263320029593662
    ticket_transcripts = 1297032714645536778
    loan_transcripts = 1300890886909202532
    booster_logs = 1297033182356574258
    bank_logs = 1299887694960267294
    straydex_logs = 1306663033162039386
    cafe_logs = 1317684614340546651

    # 🌊💙🤍───────────── _Stray_Village_1_ ─────────────💙🤍🌊

    dragonspiral_tower = 1369194566053531748
    iu = 1321322149276946544
    wrath0821 = 1371407516650438756
    sharkaev = 1361287725239505029
    tanger1nelover = 1376094678604185712
    shadowjf = 1364427842523234435
    whispering_pines_retreat = 1326160916911357972
    mienmewie = 1385641538041806930
    monika_ロ੭ = 1370900941573849168
    neurotoxz = 1373794156232835123
    mahiru_shinna = 1337349305140252694
    zenorata = 1380066122581282817
    roshidere = 1368627900554674187
    somʙяe = 1327941697031635075
    vipers_lair = 1338843550820864021
    mazril1 = 1343125464604086323
    seaweed = 1218904099999977592
    zunnun = 1274862270563881062
    something_g00d = 1361012143327285258
    the_desert = 1375715203538223144
    nanahoshi_garden = 1371088529983144030
    crazyloy = 1389775943446298768
    thatguy = 1395853163755602010
    oreo = 1305096603031310336
    balugaa = 1321390096733442112
    jutonnng = 1323305722003587182
    aquanoid19 = 1401466671914549340
    meyura088 = 1382629970890723388
    cernbonk = 1372184127532564561
    cubilo0406 = 1383993678556692562

    # 🌊💙🤍───────────── Community ─────────────💙🤍🌊

    straydex = 1298882231200387083
    suggestions = 1334502972381466698
    trending = 1106121003370827856
    filo_chat = 1243142024920567890
    off_topic = 1054016462295158805
    media = 1050380353317126154
    qotd = 1339527031217586186
    quest_help = 1056073060349911060
    as_pokemeow = 1403589642791419905
    dex_help = 1176807489786888282
    ask_for_help = 1076788196219813938
    starboard = 1329763617293467739
    captcha_help = 1387452217862258738
    pokechat = 1298468564855947296
    birthdays = 1047856018840891489
    altar = 1060853563221364736
    flex_or_fail = 1055295393031798904
    rps = 1380444905775824926
    adult_chat = 1140763487526735963

    # 🌊💙🤍───────────── Server ─────────────💙🤍🌊

    worldboss_tracker = 1281866858965762129
    rarespawn_tracker = 1055058059757625354
    onboarding = 1297197494215639100
    carl_roles = 1387257664958103552
    roles = 1047856018840891483
    welcome = 1299536346683281428
    gl_auc_feed = 1356603196520267998
    as_rare_spawn_tracker = 1403934473074245632
    partners = 1118659992342499439
    recruitment = 1074975125339914260
    achievements = 1160187203209666590
    change_log = 1299736515634663434
    milestones = 1107274235602272307
    waterstate_tracker = 1050376063965991012
    staff_intro = 1122885909659001006

    # 🌊💙🤍───────────── _Classroom ─────────────💙🤍🌊

    off_topic_ = 1280353125353394187
    the_cat_cafe = 1161974145567957052
    script = 1180728765463134238
    market_snipe = 1087334778979758110
    cuties_collector = 1051019173255446568
    iridescent = 1326967920622047313
    kei = 1090617343840894997
    judyboy = 1076489284850290778
    kiwiparti = 1076095246552797204
    nfew22 = 1131362789622042705
    empy = 1120240183938388038
    okaruns_chamber = 1307374593534595072
    khy = 1050645885844987904
    nikka = 1113851410560323654

    # 🌊💙🤍───────────── Playground_ ─────────────💙🤍🌊

    jail = 1047856020053032962
    sofi = 1216022279839023165
    p2_ffa = 1210021330762727494
    p2_sh = 1334324514749681705
    karuta = 1190533659539812462
    card_coll = 1217486177431584869
    pokebooster = 1346248362919198740
    psycord = 1191917475454001173
    mudae = 1389452074869194916
    mugshots = 1402281340019409006
    owo_central = 1140939205845975102

    # 🌊💙🤍───────────── _Admin_Hq ─────────────💙🤍🌊

    lady_gardevoir = 1282135705723605034
    khy_basement = 1297024043467407421
    xeno_lab = 1297024418605695061
    khy_office = 1297024005005508638
    xeno_office = 1297024141135970324
    important_news = 1297974697329168445
    todo_list = 1299746115725426690
    admin_chat = 1300970261377454080

    # 🌊💙🤍───────────── Monstreet_Exchange ─────────────💙🤍🌊

    cafe = 1308977690182815834
    marketplace = 1297971699597312051
    ⅲshiny_market_feed = 1298124768653873302
    ⅱl_m_gmax_market_feed = 1236634187356966922
    ⅰc_u_r_s_market_feed = 1140826976396001292
    loans = 1300847190712909875
    l5pre_mega_market = 1242760854290698332
    bakery = 1307120351314051182
    collections = 1298114332583788597
    lottery = 1343775373137154068
    ⅳgolden_market_feed = 1298126860441616434

    # 🌊💙🤍───────────── Galotto_Sponsorship ─────────────💙🤍🌊

    _1508_misamo = 1407081741406965820

    # 🌊💙🤍───────────── _Vip_Penthouse ─────────────💙🤍🌊

    ryuzzzei = 1143182156559036416
    hunter = 1331949364892925952
    xeno = 1254994357581381654
    vip_helpdesk = 1192318747344650260
    rachel = 1373940046872182825
    ditto_paradise = 1332474707525636117
    peaceful_yamper_farm = 1374796829748756691
    emma = 1297562750557356074
    themagician21 = 1340713562905116793
    ceebs1 = 1326010690430959656
    abyss = 1375654997747826740
    marge = 1399873747204178051
    janairy = 1206097741915099136
    im_yu = 1361346551124852981
    vip_chat = 1047856020430540848
    stargazing = 1369877090253541517
    roach_anti = 1050319636815683615
    drag_strip = 1328738368556892161

    # 🌊💙🤍───────────── _Events_Giveaways ─────────────💙🤍🌊

    carnivalesque = 1359856208961601638
    hunt = 1076441765059502233
    giveaways = 1297214502458232933
    clueberry = 1344468716313645157
    event_news = 1059348062063046697
    wg_giveaways = 1370966938246713394
    ga_submission = 1297227659406741504
    event_tracker = 1299764278034694214
    prize_claim = 1297255751353372825

    # 🌊💙🤍───────────── _Golden_Lands_ ─────────────💙🤍🌊

    isagi = 1313254621757571153
    misamo = 1381130164796260474
    typical_loops = 1397635371289804842
    libbynico = 1293261052745875537
    bunny_cave = 1335884394967207957

    # 🌊💙🤍───────────── _Bronze_Meadows_ ─────────────💙🤍🌊

    sinjan0537 = 1403991965057683567
    narus_garden = 1396398076750463157
    dearestsibling = 1383901114826752021
    crows_nest = 1349446569392476201
    daren88 = 1391477366634709073
    frayl = 1340943773550641194
    scarlet = 1305951922884317257
    _0rz_ = 1406854795603607693
    vlntno_o = 1395624967386955887
    skyfall = 1363568407785640027
    just_oni = 1391323045360308295
    fadedfr = 1405209290460889119
    mpyds = 1327975994606485589

    # 🌊💙🤍───────────── _Straymons ─────────────💙🤍🌊

    feeling_lucky = 1140856137344892978
    goal_tracker = 1074600794923470869
    straybie_orientation = 1306600686519324682
    clan_treasury = 1368252645755719690
    intros = 1125838440987103302
    claw_machine = 1343944894963519570
    clan_rules = 1175146788613783643
    clan_bank = 1298166528084017253
    clan_chat = 1279801225432273048
    bumps = 1049890490931216444

    # 🌊💙🤍───────────── _Staff_Lounge ─────────────💙🤍🌊

    as_rare_spawns = 1403865683657490565
    staff_commands = 1297295587271639060
    compte_rendu = 1342170604492689524
    bad_noodles = 1178261036474843238
    airport = 1297195824018886708
    staff_reminders = 1143317163025907802
    staff_announcement = 1373402906904100964
    staff_lounge = 1297028770548416532
    ms_reports = 1326751403514920960
    reports = 1299823993011961866
    clan_stats = 1143325539772403712

    # 🌊💙🤍───────────── _Silver_Hills_ ─────────────💙🤍🌊

    jecfr = 1358295641628868639
    churro = 1305173058260176987
    underdog = 1395435942512431174
    ani = 1381636082470355045
    blue = 1267649792087953408
    eggplant_dave = 1307886910567350323
    purin = 1401633427081531463
    skies_of_ember = 1350759664651997335
    steffilah = 1361353346287403359
    _dengerous = 1380068767480152134

    # 🌊💙🤍───────────── Help_Desk ─────────────💙🤍🌊

    _1528_mynameislau2003 = 1409223880287060128
    _1526_ryuzzzei = 1408978860799819828
    gard_helpdesk = 1297042837518549034

    # 🌊💙🤍───────────── _Short_Ga_Submissions ─────────────💙🤍🌊

    _1530_sakikiru = 1409438150442483803
    _1529_lovely_batter = 1409310026702786651

    # 🌊💙🤍───────────── _Archive_Tickets_ ─────────────💙🤍🌊

    dump = 1188685111483441202

    # 🌊💙🤍───────────── _Probation_ ─────────────💙🤍🌊

    sakikiru = 1409160625619206305
    mynameislau2003 = 1409140303985643553
    dump = 1395082312198258798

    # 🌊💙🤍───────────── Leave_Of_Absence ─────────────💙🤍🌊

    _1525_daren88 = 1408737327567736862
    _1527_xanix = 1409111803463729223

    # 🌊💙🤍───────────── _Bingo_ ─────────────💙🤍🌊

    bingo_info = 1293403573924663346
    staff_event_chat = 1290073142815100979

    # 🌊💙🤍───────────── Open_Sanctuary_ ─────────────💙🤍🌊

    hoenn_spot = 1209110434137772042
    johto_grove = 1172017556635275274
    kanto_park = 1146336853180563517
    unova_forest = 1298764697754927155

    # 🌊💙🤍───────────── _Long_Ga_Submissions ─────────────💙🤍🌊

    _1475_bunny_silly = 1404074396750184480

    # 🌊💙🤍───────────── _Diamond_Fields_ ─────────────💙🤍🌊

    dancraft = 1310388655117828126
    ash = 1167845743957131335


# 💦☁────────────────────────────────────────────💦☁
#       STRAYMONS__VOICE_CHANNELS
# 💦☁────────────────────────────────────────────💦☁
class STRAYMONS__VOICE_CHANNELS:

    # 🌊💙🤍───────────── _Staff_Lounge ─────────────💙🤍🌊

    staff_vc = 1297034566850314241

    # 🌊💙🤍───────────── Uncategorized ─────────────💙🤍🌊

    online_members_94 = 1299903761808101517

    # 🌊💙🤍───────────── _Straymons ─────────────💙🤍🌊

    custom_vc = 1298110095405617163

    # 🌊💙🤍───────────── Community ─────────────💙🤍🌊

    voice_channel = 1299902233613438996


# 💦☁────────────────────────────────────────────💦☁
#       STRAYMONS__STAGE_CHANNELS
# 💦☁────────────────────────────────────────────💦☁
class STRAYMONS__STAGE_CHANNELS:

    # 🌊💙🤍───────────── Uncategorized ─────────────💙🤍🌊

    straymons = 1299902922779529347


# 💦☁────────────────────────────────────────────💦☁
#       STRAYMONS__NEWS_CHANNELS
# 💦☁────────────────────────────────────────────💦☁
class STRAYMONS__NEWS_CHANNELS:

    # 🌊💙🤍───────────── _Admin_Hq ─────────────💙🤍🌊

    xeno_hdd = 1285358207446814801
    fidshop = 1313670085285642311
    khy_notebook = 1297024106772037693

    # 🌊💙🤍───────────── Community ─────────────💙🤍🌊

    library = 1054706616869605436
    primrose_garden = 1337610636699369524

    # 🌊💙🤍───────────── Server ─────────────💙🤍🌊

    announcement = 1297195970462744597
    os_news = 1297196674279538839

    # 🌊💙🤍───────────── _Staff_Lounge ─────────────💙🤍🌊

    staff_meeting = 1304450270633394186
    staff_handbook = 1297028846524301413

    # 🌊💙🤍───────────── _Straymons ─────────────💙🤍🌊

    straymon_news = 1074601415365898281

    # 🌊💙🤍───────────── Playground_ ─────────────💙🤍🌊

    bot_commands = 1216228569185914890


# 💦☁────────────────────────────────────────────💦☁
#       STRAYMONS__CATEGORIES
# 💦☁────────────────────────────────────────────💦☁
class STRAYMONS__CATEGORIES:

    _AI_SYSTEMS = 1297013895248085073
    _STRAY_VILLAGE_1_ = 1344580432796192838
    COMMUNITY = 1297287409926541433
    SERVER = 1297188854583005266
    _CLASSROOM = 1125010172906061824
    PLAYGROUND_ = 1047856019742666754
    _STAFF_LOUNGE = 1297017136635449364
    _ADMIN_HQ = 1297013680747057223
    MONSTREET_EXCHANGE = 1297287523818536991
    GALOTTO_SPONSORSHIP = 1311836611486552074
    _VIP_PENTHOUSE = 1047856020430540847
    _EVENTS_GIVEAWAYS = 1297195708922724432
    _GOLDEN_LANDS_ = 1089194020443529246
    _BRONZE_MEADOWS_ = 1259790123864686602
    _STRAYMONS = 1297730116549345322
    _SILVER_HILLS_ = 1093456090341056522
    HELP_DESK = 1297042273824931895
    _SHORT_GA_SUBMISSIONS = 1297237066316386324
    _ARCHIVE_TICKETS_ = 1188682738635644990
    _PROBATION_ = 1379963100291268758
    LEAVE_OF_ABSENCE = 1311831669921157221
    _BINGO_ = 1375712227734061126
    OPEN_SANCTUARY_ = 1079044244272054383
    _LONG_GA_SUBMISSIONS = 1297237107357515786
    _DIAMOND_FIELDS_ = 1050374900902281277


# 💦☁────────────────────────────────────────────💦☁
#       STRAYMONS__ROLES
# 💦☁────────────────────────────────────────────💦☁
class STRAYMONS__ROLES:

    xeno = 1258992854764621835
    straymons_overseer = 1282129009970380853
    pokemeow = 1050318651301056554
    meowhelper = 1239104082338381896
    resident_woop = 1398892692376653967
    pastry_pooch = 1311553969809657959
    _unknown = 1312218343381536781
    mee6 = 1137441144708546662
    carl = 1048011443531952140
    mimu = 1048012646236041330
    dyno = 1173707290868727861
    not_quite_nitro = 1061934789793435650
    chroniclebot = 1311919541495926846
    bump_reminder = 1049700272873680929
    discobot = 1048897118150074371
    jockie_music_b = 1285196369413541943
    jockie_music_o = 1297311749988679805
    jockie_music_t = 1297311800047566898
    memberlist = 1112489996931301439
    owo = 1130679973942927484
    pixxiebot = 1048066570523508799
    quickvids = 1050059888665034835
    giveaway_boat = 1130362872912953386
    stickybot = 1297217271114104926
    thread_watcher = 1191843703283781674
    discohook_utils = 1305864022037495840
    altar_boy_ralts = 1312627942718963734
    ash_ketchum = 1298667082694787082
    fidough = 1283550799296991242
    pikachu = 1298667400019050536
    team_rocket = 1298666872308367451
    deadpool = 1287262630431555595
    spider_man = 1287265866941071473
    birthday_donut = 1048240291561349172
    prisoner = 1172874250810556466
    non_weekly = 1173567638253875260
    absent = 1185923762630180994
    poke_water = 1311097424055369769
    bao_buns = 1049331545653133383
    blue_lagoon_pie = 1048458820420108329
    caregivers_delight = 1049331704503992362
    celestial_berry_bliss = 1126093176810258463
    ethereal_eclair = 1126093765451456593
    frosted_tart = 1048458080293228615
    layered_cream_puff = 1048460710990069760
    meadow_matcha = 1049331020190732368
    midnight_chocolate_eclipse = 1126094052559958097
    strawberry_flame_cupcake = 1126092717013864498
    zesty_lemon_pie = 1126093397875249242
    vip = 1050315954254520390
    khy_empy = 1047856017528074332
    empy_khy = 1135640725179072532
    the_knave = 1282134605545341072
    fluorescence = 1326968847764557966
    absol_addict = 1328982316051337236
    shitto_lover = 1335418387165216768
    the_traveler = 1346546704891117579
    mlem = 1330409361939496991
    complete_degenerate = 1374798294760554576
    nubzei = 1373236281496174683
    hoshiyomi = 1373244549190778920
    magic = 1349918886522392576
    the_honored_one = 1332132590567559340
    stitchlover = 1329948481015513088
    occult_kun = 1326182567895891989
    hisuian_zorua = 1281624886246248548
    glaceon = 1110543113409282059
    psyduckie = 1199129178646257758
    jan = 1253564843882057749
    annoying_dog = 1142156459975651470
    poliwag = 1055046189868916787
    x = 1301220959369298020
    ghostie = 1199652288537579600
    shiny_queen = 1377055810139455549
    odd_ish = 1404516635146190918
    gamebots = 1297312266328211537
    hideaki = 1216407095797223509
    karuta = 1048180090934132768
    karuta_helper = 1198583564611104890
    pokedream_go = 1191917919320424540
    poketwo = 1210021710871400491
    poketwo_helper = 1210021934012702722
    queens_right_leg = 1217289741192658986
    rinbot = 1053098429863186524
    sofi = 1216022522114478183
    sofu = 1216023466118090785
    starflight = 1199370063719972956
    pokebooster = 1346248805166612603
    perm_mods = 1285356699665825885
    clan_owner = 1087559258784137276
    clan_co_owner = 1110487573987594300
    clan_bank = 1142703276299665418
    clan_staff = 1151710977193152512
    achievements = 1297226525132980235
    buffs = 1311713255525322792
    top_catcher = 1109746736227962892
    floriane = 1311427467906515074
    bloomia = 1311427689282011198
    seedlet = 1311427994728009729
    monthly_grinder = 1202405438415442011
    weekly_grinder = 1110493317260660787
    weekly_angler = 1341703395421065267
    weekly_guardian = 1341703458964766780
    server_booster = 1050310714696413184
    dulce_ditto = 1311426157882900512
    bananapod = 1311427801101897798
    charred_kimchi = 1311408723960266813
    karpyaki = 1311408803111112755
    spicy_goldtoro = 1317238559954178069
    charmaki = 1317238438654644304
    mewnigiri = 1317238670264238190
    chikorita_rolls = 1311426051204714536
    clefberry_chews = 1317239384654745622
    gengrape_chews = 1317239491592978482
    snorice_ball = 1311426237339795498
    peach_elixir = 1313939766726889503
    charming_hershey_espresso = 1311408569945686138
    ember_tea = 1311427912116736001
    sandwich = 1311427573099794492
    completionist = 1200835775881814026
    levels = 1160189904496623749
    mew_lvl_50 = 1159971737576951869
    cosmog_lvl_40 = 1159970623892758648
    xerneas_lvl_35 = 1159896202314252378
    sprigatito_lvl_30 = 1159970100984688680
    pikachu_lvl_25 = 1159894833847074967
    latias_lvl_20 = 1159893129730736199
    pawmi_lvl_15 = 1159890032908324944
    igglybuff_lvl_10 = 1159887619208003676
    pachirisu_lvl_5 = 1048443981824004136
    info = 1047877253897392158
    probation = 1379961959377670205
    rookie = 1113433599006490644
    straybie = 1309094588685750352
    straymon = 1074599245744713809
    stray = 1163723705441062963
    waiting_list = 1213087560973291521
    trainer = 1297017856667680840
    donated = 1129889044650807458
    not_donated = 1112486591043223632
    blessed = 1312069554616402011
    low_spirit = 1312071103136665673
    patreon = 1091520227759636482
    non_patreon = 1133034419570102344
    espresso = 1140757804320305283
    meowhelper_registered = 1236457369160913018
    buddy = 1311426465786761378
    _500 = 1344159394920927333
    _250 = 1344159311563325441
    onboarding = 1297225631989501964
    adult = 1047879581237006336
    minor = 1047879683749982268
    africa = 1047945687356153948
    asia = 1047945356664647760
    europe = 1047945307209613342
    oceania = 1047945879627255808
    n_america = 1047945428412399667
    pinoy = 1234021606272008213
    s_america = 1047945489473093674
    sheher = 1047884245181399110
    hehim = 1047884315603771463
    theythem = 1047884397241700372
    use_my_name = 1047944542185336923
    any_pronouns = 1047945168311033886
    pings = 1047878933443530843
    access = 1297249977864814622
    ga_banned = 1112709445764522074
    event_host = 1407118330627620984
    golden_ticket_holder = 1311492103238455380
    sga_entry_ticket = 1287163588502360124
    sga_host = 1299617478321897492
    sga_winner = 1298943135711363132
    lga_entry_ticket = 1299845019892580352
    lga_host = 1299844997281087499
    lga_winner = 1302074591354552380
    giveaway = 1144221472794083419
    event_participant = 1219899190205743134
    treasury = 1117122677736480978
    os_lottery = 1222023062770286714
    lottery = 1228568494241484882
    trade_ads = 1082563153113653309
    playground = 1048413210249805885
    pokemon_professor = 1300149332615368776
    quest_helper = 1161493807209132032
    hunter = 1336916905575055392
    captcha_helper = 1113046418307944510
    shiny_bonus = 1311426265152094278
    daily = 1232861400041259029
    calm_waters = 1209352148467454023
    world_boss_spawn = 1251521821807743079
    patreon_auctions = 1315126162246209697
    golden_waters = 1232861519012958300
    dawndusk = 1370227188942503996
    poketwo_rs_ping = 1247430819233009704
    _ping_karuta = 1223754347150839888
    server_drop_ping = 1215993934891716638
    wishlist_ping = 1216079440761847840
    sofi_player = 1216398325855551548
    ee_ping = 1362786557937057872
    perfumista = 1378595066217496617
    bot_status = 1377110983281217626
    snipe = 1099686147548004432
    dugoyaki = 1239750178995703858
    pawcky = 1242760459187130378
    hello_pandlax = 1241970602764406804
    pastry_lover = 1322361253309710419
    spooky_hour = 1294417356021301249
    golden_snipe = 1232862101123366972
    shiny_snipe = 1219193613825609770
    gmax_snipe = 1331906680472211510
    mega_snipe = 1331906944763432991
    legendary_snipe = 1232862266605441024
    super_rare_snipe = 1232862383895216230
    basic_snipe = 1331906510581796877
    gigantamax_pokebots = 1297039831221932062
    parfait = 1317242880011538473
    mega_pokebots = 1297020130798211083
    pokebots = 1297335109028020255
    muted = 1346759966270165083
    cinnamon = 1388086495721689168
    mudae = 1389451866198376530
    as_rs_ping = 1403931416038735914
    as_spawn_ping = 1405007495755337828
    espeon = 1409761296169304066
    sunrise_scone = 1409756540570828821


# 💦☁────────────────────────────────────────────💦☁
#       STRAYMONS__EMOJIS
# 💦☁────────────────────────────────────────────💦☁
class STRAYMONS__EMOJIS:

    lurk = "<:Lurk:1048131442426785833>"
    cry = "<a:Cry:1095037882084892753>"
    magical_heart = "<a:magical_heart:1048253358500233226>"
    magicly_w_hoesmad1 = "<a:Magicly_w_hoesmad1:1048809608401133598>"
    kleeheart = "<:KleeHeart:1050399757035643000>"
    hutao_facepalm = "<a:Hutao_facepalm:1050400038376976435>"
    moneyz = "<:Moneyz:1050401081957556275>"
    yatocat = "<:YatoCat:1050406923704488058>"
    kiss = "<a:kiss:1096387804935749674>"
    albedofawn = "<a:AlbedoFawn:1050421623511076864>"
    tired = "<a:tired:1050530905577496586>"
    sad = "<:sad:1164488850807197767>"
    panda_walkaway_animated = "<a:Panda_WalkAway_Animated:1050530915400548473>"
    panda_popcorn_animated = "<a:Panda_Popcorn_Animated:1050530922979672145>"
    wtf = "<:wtf:1234385076435816599>"
    coffee = "<:coffee:1050530930462298273>"
    sweat = "<a:sweat:1097741284443177051>"
    pikapout = "<:pikapout:1050781799422373978>"
    vulpix_sleep = "<:vulpix_sleep:1050781804229050479>"
    pokemon_slap = "<a:pokemon_slap:1050781808217833574>"
    eevee_think = "<:eevee_think:1050781844825706496>"
    fire = "<a:fire:1124148731147714560>"
    clap = "<a:Clap:1100937995751805019>"
    sylveon_cute = "<:sylveon_cute:1050800831634612306>"
    money = "<a:Money:1050800902182805594>"
    slowpokehuh = "<:SlowpokeHuh:1050801043719602257>"
    stressedpsyduck = "<:StressedPsyduck:1050801384917848225>"
    yaranaikachu = "<:YARANAIKACHU:1050801506686861404>"
    sylveon_smug = "<:Sylveon_Smug:1050801817996501053>"
    charizard_think = "<:Charizard_Think:1050801880915259423>"
    snowpix_cry = "<:Snowpix_Cry:1050802193948749864>"
    pat = "<a:pat:1140251972243574784>"
    pika_gun = "<:Pika_Gun:1050802514859143268>"
    oshawootsad = "<:OshawootSad:1050802993156595833>"
    bulbaconfused = "<:BulbaConfused:1050803242067574806>"
    psywhat = "<:PsyWhat:1050803289417076776>"
    giggle = "<a:giggle:1095508639088906341>"
    heal = "<:Heal:1051105408288313375>"
    pikachu_icon = "<:pikachu_icon:1057252076423499776>"
    pika_cute = "<:pika_cute:1061247532635783238>"
    laxsleep = "<:LaxSleep:1061502544427368589>"
    bulbasmirk = "<:BulbaSmirk:1061502836199927848>"
    flareonsip = "<:FlareonSip:1061503876341178389>"
    pikathumbsup = "<:pikathumbsup:1061504363849326702>"
    pikaomg = "<a:pikaOMG:1061515556680896562>"
    eevee = "<a:eevee:1067303566575927356>"
    pokemon_wink = "<a:pokemon_Wink:1067303580110966825>"
    magikarp = "<:magikarp:1067303592161194034>"
    violin = "<a:violin:1075618564066779227>"
    aaaa = "<:AAAA:1077928434623316050>"
    twerkalien = "<a:twerkalien:1081495408221634560>"
    grimchamp = "<:GrimChamp:1081556291517943840>"
    yellow_sparkles = "<a:yellow_sparkles:1082087052394385480>"
    espeonlove = "<:EspeonLove:1084696424630997012>"
    leafeonblush_rs = "<:LeafeonBlush_RS:1084833749314834583>"
    pikalove_rs = "<:pikalove_RS:1084833872124063844>"
    ppikasparkle_rs = "<a:ppikasparkle_RS:1084834191939735582>"
    shiny_eevee = "<:Shiny_Eevee:1084834289826410526>"
    duckf_035 = "<:duckf_035:1084834453102272632>"
    sobble_cry = "<:sobble_cry:1084834775363223632>"
    umbreon_rnbw_rs = "<a:umbreon_rnbw_RS:1084836141498376212>"
    evilpika = "<:EvilPika:1084836304157687868>"
    eevee_cool = "<:Eevee_Cool:1084836490472853537>"
    ditto_woah = "<:ditto_woah:1085442309094637649>"
    peek = "<a:peek:1139398415965495306>"
    bounce = "<a:bounce:1139330402524348466>"
    dragonite_hi = "<:dragonite_hi:1085443561044049990>"
    litwick_thumbs_up = "<:litwick_thumbs_up:1085443855740047390>"
    espeon_uwu = "<:espeon_uwu:1085532224897699970>"
    litwickdance = "<a:litwickdance:1085976261144350800>"
    sylveonsip = "<:sylveonsip:1085976678758617118>"
    sylveonscream = "<:sylveonscream:1085976840860074105>"
    sylveonwave = "<:sylveonwave:1085976978299031562>"
    uwu = "<a:uwu:1097686415095103678>"
    woopershout = "<a:woopershout:1085977556085379113>"
    celebi_question = "<:celebi_question:1086856498262573056>"
    te_pc = "<:te_pc:1087620888091971635>"
    kekhands = "<:kekhands:1087625865728380969>"
    exit = "<a:exit:1087626014181568572>"
    bulbasaursip = "<:bulbasaursip:1088347112162467880>"
    squirtle_derp = "<:squirtle_derp:1088639978587824190>"
    duckthinks_017 = "<:DuckThinks_017:1089510776030646343>"
    legendary = "<:Legendary:1090640224125718570>"
    shiny = "<:Shiny:1090640278999810079>"
    th_arrow2 = "<a:TH_Arrow2:1091136664027537499>"
    frogheart = "<:frogheart:1091275676990062653>"
    psyduck_sweat = "<:psyduck_sweat:1091345884761042944>"
    pc_squirtleheadbop = "<a:pc_SquirtleHeadBop:1091607211517693972>"
    dog_kek = "<:Dog_Kek:1092079556317433886>"
    grookey_think = "<:grookey_think:1092696086524731412>"
    jirachi_woah = "<:jirachi_woah:1092696218766954576>"
    look = "<a:look:1092696367337570395>"
    pog = "<a:POG:1092696429165809685>"
    mimikyu_lurk = "<:mimikyu_lurk:1092698997023588372>"
    mew_heart = "<:mew_heart:1111416850987896933>"
    pokemon_periodt = "<:pokemon_periodt:1092704659837288468>"
    pikachu_derpface = "<:pikachu_derpface:1092705202211131413>"
    koko_sus = "<:koko_sus:1092769511947649025>"
    heart = "<a:heart:1187397600807235635>"
    pikastop = "<:pikastop:1093546503194300546>"
    pika_pat = "<:pika_pat:1093546592503611523>"
    pika_breakdown = "<:pika_breakdown:1093546769763287100>"
    eevee_ded = "<:eevee_ded:1093547474121150485>"
    umbhuh = "<:umbHUH:1093547658100101170>"
    _1jigglypuff_sparkle = "<:1jigglypuff_sparkle:1093547795681652837>"
    meloetta_shy = "<:meloetta_shy:1093548014259413162>"
    snorlax_glare = "<:snorlax_glare:1093548035000258580>"
    pachirisu_gimmie = "<:pachirisu_gimmie:1093548097788973086>"
    oshawott_sip = "<:oshawott_sip:1093548243826266133>"
    th_pray = "<a:TH_Pray:1093557231171145728>"
    patrick_business = "<:patrick_business:1093602933448396880>"
    shut = "<:shut:1093615742110408794>"
    unshut = "<:unshut:1093618250581020785>"
    slowpoke_clap = "<a:slowpoke_clap:1093622697302446201>"
    evil = "<a:evil:1111240977114468352>"
    teddiursa_happy = "<:teddiursa_happy:1093624842797994035>"
    shinymega = "<:ShinyMega:1093693314647212122>"
    sheesh = "<:Sheesh:1134522823315046400>"
    wooper_mindblown = "<a:wooper_mindblown:1093737523957747754>"
    slap = "<a:slap:1149426959584083998>"
    slap_back = "<:Slap_Back:1093738218333151242>"
    pikahat = "<:pikahat:1093738671053738045>"
    sobble_pray = "<:sobble_pray:1095027568891146360>"
    sobble_sus = "<:sobble_sus:1095027642408906774>"
    nod = "<a:nod:1095037712236552223>"
    shy = "<a:shy:1095037799805235312>"
    gift = "<a:gift:1095038343324119152>"
    bow = "<a:bow:1098123294751871038>"
    flareon_cry = "<:flareon_cry:1095390414976073768>"
    frog_vibing = "<a:frog_vibing:1095507224564093089>"
    frog_heart = "<:frog_heart:1095507405573460020>"
    jolteon_heart = "<:jolteon_heart:1095508115685908560>"
    ok = "<a:ok:1095508389095821342>"
    no = "<a:no:1141677836948754553>"
    buttonlovewhitepinktwitch = "<a:buttonlovewhitepinktwitch:1095509208931258388>"
    peaceout = "<a:PeaceOut:1095509650662772837>"
    simp = "<:simp:1095726673300828291>"
    charangry = "<:charangry:1096386081664028813>"
    flower = "<a:flower:1098123576160292945>"
    _05_cheerleders = "<a:05_CHEERLEDERS:1096388097773670430>"
    eevee_salute = "<:eevee_salute:1096918959997079692>"
    think = "<:think:1097056702911750195>"
    vaporeonsad = "<:vaporeonsad:1097057347018440756>"
    sorry = "<a:sorry:1097300107625500764>"
    wow = "<a:wow:1131910076140101673>"
    blush = "<:Blush:1214135088447619093>"
    frogsus = "<:frogsus:1098036702964093049>"
    au_goodluck = "<a:AU_goodluck:1098123035392876584>"
    wooper = "<a:wooper:1098125095920205854>"
    espeon_surprised = "<:Espeon_Surprised:1098125100273901630>"
    espeon_sad = "<:espeon_sad:1098125105915236412>"
    espeon_angry = "<:espeon_Angry:1098125111770480670>"
    goodnight = "<a:goodnight:1098215968397856819>"
    sus = "<:sus:1098602662951391242>"
    judgementlax = "<:JudgementLax:1098615945590751282>"
    umbreon_angel = "<:Umbreon_angel:1098616025873928202>"
    l_ = "<a:L_:1098616113367089213>"
    ll_loveletter2 = "<a:LL_loveletter2:1099665664366628904>"
    sniper = "<:Sniper:1099687254051541042>"
    pepeevil = "<:PepeEvil:1099764207232241686>"
    guitar = "<a:guitar:1100072807125241928>"
    keklet = "<:keklet:1100072911777308782>"
    mega = "<:Mega:1103366444521111592>"
    fear = "<:fear:1106017650900996129>"
    chappal = "<:chappal:1106018677788246118>"
    note = "<a:note:1108291134112923668>"
    ghost = "<a:ghost:1109263561856925817>"
    spheal_bap = "<a:spheal_bap:1109654560466804747>"
    spheal_lazy = "<:spheal_lazy:1109654779954729020>"
    gengarpout = "<:gengarpout:1110213466096152606>"
    sphealove = "<:sphealove:1110808753810460682>"
    eeveecandies = "<:eeveecandies:1110917768125108286>"
    bulba_flowers = "<:bulba_flowers:1113074697005961237>"
    dance = "<a:dance:1114353626165542952>"
    tap = "<a:tap:1114355953664528480>"
    spongebobbruh = "<:spongebobbruh:1115952332069404744>"
    bonk = "<a:Bonk:1116995304177291394>"
    pray = "<a:pray:1117768129007865927>"
    puppray = "<:PupPray:1117768185953914910>"
    sulk = "<a:sulk:1118006309120380939>"
    heart_purple = "<a:heart_purple:1119769604001124422>"
    emoji_sparkles = "<a:Emoji_Sparkles:1121306875007348808>"
    poke = "<a:Poke:1121797611880456262>"
    mew_hi = "<:mew_hi:1122086001901322340>"
    mew_blush = "<:Mew_blush:1122086037284454462>"
    angelvulpix = "<:AngelVulpix:1122458319160868895>"
    businessspheal = "<:BusinessSpheal:1122458399905431632>"
    thistbh = "<:thistbh:1122555445471621130>"
    sylveonuwu = "<:sylveonuwu:1122878723813801994>"
    umbreon_tea_shiny = "<:umbreon_tea_shiny:1122973324931244042>"
    catsmug = "<:CatSmug:1122974540457324659>"
    music = "<:music:1123479254940786728>"
    eevee_cute = "<:eevee_cute:1137386674683392051>"
    nyanhewwoowo = "<:nyanhewwoOwO:1124148152119869450>"
    run = "<a:run:1124148385860034570>"
    vulpixsleep = "<:vulpixsleep:1124887688403767388>"
    vibe = "<a:vibe:1126378795717361705>"
    stairs = "<a:stairs:1126383751463702589>"
    sylveon_shy = "<:sylveon_shy:1126401628652720188>"
    idonotseeit = "<:idonotseeit:1127079484835774484>"
    poledancing = "<a:PoleDancing:1127223123536785519>"
    cat_cute = "<:cat_cute:1127557714504077422>"
    popcorn = "<a:popcorn:1137425056486662275>"
    _1_ = "<a:1_:1128420495004545185>"
    congrats = "<a:congrats:1128854264077357138>"
    lenility_holo_stars = "<a:lenility_holo_stars:1130020885311528981>"
    wh_pinkarrow = "<:WH_pinkarrow:1130023348747911188>"
    gbg_marillheart = "<:GBG_marillheart:1130049054634692648>"
    wall = "<a:wall:1130049449524211712>"
    beg = "<a:beg:1130060418040209498>"
    laugh = "<a:laugh:1130123548204204072>"
    judging = "<a:judging:1130123590235324539>"
    cocohype = "<:CocoHype:1131204436757331968>"
    teddiknife = "<:TeddiKnife:1131204548476813412>"
    eeveehmm = "<:eeveehmm:1131204716639047680>"
    grumpyflareon = "<:GrumpyFlareon:1131516178276294686>"
    vulpixuwu = "<:vulpixuwu:1131917986928787456>"
    _4799_arrow_heart = "<a:4799_arrow_heart:1132347328922132500>"
    k_roll = "<a:k_roll:1132897252709511168>"
    superrare = "<:SuperRare:1133025503067000852>"
    vaporcorn = "<a:vaporcorn:1134370443537694831>"
    mudkipheart = "<:MudkipHeart:1134370665273757726>"
    frozenkenpodance = "<a:FrozenKenpoDance:1135057561360551946>"
    a_needrn = "<a:a_needrn:1135372151361372252>"
    _93_pandadanceduck = "<a:93_pandadanceduck:1135490575190216785>"
    aupinching = "<a:AUPinching:1135536472829739058>"
    auadie = "<a:AUadie:1135536582884073553>"
    cattocry = "<:cattocry:1137030161007648808>"
    eeveethankyou = "<:eeveethankyou:1137385369919299738>"
    happydance = "<a:happydance:1137386093537407006>"
    bcaguiltysweat = "<a:bcaGuiltySweat:1137423691119087727>"
    wine = "<a:wine:1137425701105045505>"
    fishbite = "<:Fishbite:1137448368583491647>"
    smoljail = "<:smolJail:1137634803353653258>"
    fish = "<a:fish:1137914837775699978>"
    kekw = "<:kekw:1138296554843811931>"
    obwdeadowo = "<a:obwDeadOwO:1138684894810226788>"
    qtbearlaugh = "<a:qtbearlaugh:1139115548047839252>"
    confused = "<a:confused:1139397939731632181>"
    popcornchomp_rs = "<a:PopcornChomp_RS:1139439928917372938>"
    carlderp = "<:carlderp:1142116334554075176>"
    rare = "<:Rare:1142668430634393610>"
    pikalaugh = "<:pikalaugh:1144638869497716856>"
    evilbunny = "<a:EvilBunny:1144664496942612551>"
    be_stickbugged = "<a:BE_Stickbugged:1144826396431089664>"
    cat_stare = "<a:Cat_stare:1146564169743745145>"
    worrypat = "<:WorryPat:1146721877994262658>"
    hype = "<a:Hype:1213073010559426590>"
    bike2 = "<a:bike2:1146747718392365056>"
    hello = "<a:hello:1146767425686208543>"
    bruh = "<:BRUH:1146828766262337536>"
    sadcat = "<:SadCat:1146854703515316364>"
    abt_wingsblue = "<a:abt_wingsblue:1146855247751434390>"
    cathax = "<:cathax:1146969267556847637>"
    touchgrass = "<a:touchgrass:1146970080282947654>"
    bsdance = "<a:bsdance:1147367456088805496>"
    froggepoof = "<a:froggepoof:1147367554269052998>"
    catno = "<a:catno:1147367608962793572>"
    hmmmcloseupzoom7 = "<a:hmmmcloseupzoom7:1147367687173976145>"
    roll2 = "<a:roll2:1147369580684128256>"
    roll1 = "<a:roll1:1147369636891992084>"
    pe_nikkihype = "<a:PE_NikkiHype:1147482233813340240>"
    bunny = "<a:bunny:1147775795146805341>"
    golden11 = "<:Golden11:1147776276510281818>"
    shrug = "<a:shrug:1148289155063885854>"
    raiseeyebrows = "<a:raiseeyebrows:1148590053510094890>"
    pepescam = "<a:pepescam:1148639128720785608>"
    bird_swing = "<a:bird_swing:1148811018420621462>"
    noot = "<a:noot:1148878556064133161>"
    kekcry = "<:kekcry:1148963255071559691>"
    chimkinnuggy = "<:chimkinnuggy:1149507264974180353>"
    disappear = "<a:disappear:1149726463705231392>"
    marshluv = "<:MarshLuv:1149949267662864404>"
    richhutao = "<a:RichHuTao:1150280941210710087>"
    pingu_stare = "<:pingu_stare:1150367038267727973>"
    comforthuggie = "<a:ComfortHuggie:1150565498019393707>"
    catsad55 = "<:catSad55:1150878083994366003>"
    please = "<a:please:1157461454895710288>"
    doggo_boop = "<a:doggo_boop:1158575145493987479>"
    sprigatitoloading = "<a:sprigatitoloading:1159546969316925572>"
    beat = "<a:beat:1160359953081585745>"
    derp = "<:derp:1166899077275983922>"
    pikachuhug = "<:PikachuHug:1163746611634131025>"
    skityeet = "<a:skityeet:1164106800711340032>"
    glare = "<:Glare:1164207890584842330>"
    sadkermit = "<:SadKermit:1164389369013088347>"
    zaciandance = "<a:zaciandance:1165616356100685844>"
    patpat = "<a:patpat:1165758413721059388>"
    spin = "<a:spin:1166015359875297431>"
    minnosowo = "<a:minnosOwO:1166228461736693800>"
    pokecoin = "<:PokeCoin:1166253401546436648>"
    hoho = "<:hoho:1166899428494409778>"
    cleaningthatcringe = "<a:cleaningthatcringe:1167209231133450290>"
    dog_swag = "<:dog_swag:1167271358934298737>"
    bana_gun = "<:bana_gun:1167852949662355717>"
    checkthepins = "<a:CheckThePins:1168198107410989116>"
    bcazombiepray = "<a:bcaZombiePray:1169610657327485018>"
    kissmybulbass = "<:kissmybulbass:1170036725821734912>"
    sphealbounce = "<a:sphealbounce:1171096214473818192>"
    sphealsleep = "<a:sphealsleep:1171096235483090974>"
    cute_blue_bear_heart = "<a:cute_blue_bear_heart:1180767651941863465>"
    common = "<:Common:1186968566063435786>"
    uncommon = "<:Uncommon:1186968571839000606>"
    cuteheart1 = "<a:cuteheart1:1186969187869016096>"
    ty1 = "<a:ty1:1186969663519870976>"
    logogenantcym = "<a:LogoGenantCYM:1191231855320629279>"
    psysussy = "<a:psysussy:1201124362045095937>"
    sleepybaggy = "<a:sleepybaggy:1201656482467422270>"
    chipicat = "<a:ChipiCat:1202062568760553492>"
    rizzychad = "<:RizzyChad:1202592119190192148>"
    psyduckroll = "<a:psyduckroll:1203872865380868096>"
    eeveedrive = "<a:eeveedrive:1207954639799193630>"
    eevee_angel1 = "<a:eevee_angel1:1207954655678697502>"
    waddle = "<a:Waddle:1209112348988538890>"
    sprigalove = "<:sprigalove:1210775122789797908>"
    derpteri = "<:DerpTeri:1211989490281746462>"
    sphealpeak = "<:sphealpeak:1212028162234392576>"
    cutebunnyclapping = "<a:cutebunnyclapping:1212036948680642570>"
    nu_girllove = "<a:nu_GirlLove:1213166710874574848>"
    kleestrawberry = "<:kleestrawberry:1214134103474180147>"
    kleecoffee = "<:kleecoffee:1214134478457409546>"
    gasp = "<:Gasp:1214135108638867456>"
    love = "<:Love:1214135114276151306>"
    leafeon_hmm = "<:leafeon_hmm:1215397567412707378>"
    chansey_blush = "<:chansey_blush:1215398101750255616>"
    butterfree = "<a:butterfree:1215636501493317652>"
    glaceonblankie = "<a:glaceonblankie:1215637971210862713>"
    glaceonhug = "<a:glaceonhug:1215637993893924905>"
    clefairyuwu = "<a:clefairyuwu:1215638880011812966>"
    glaceoncute = "<a:glaceoncute:1215638904254894090>"
    happinydance2 = "<a:happinydance2:1215638925289332756>"
    espeonwave = "<a:espeonwave:1215639507437617202>"
    jigglypuffangry = "<a:jigglypuffangry:1215639566459863041>"
    nko_thisisfine_hell_fire = "<a:nko_thisisfine_hell_fire:1215999135199789126>"
    flip_table = "<a:flip_table:1217123103000232068>"
    wobbulove = "<a:WobbuLove:1217408870817726535>"
    afoxy_hug = "<a:AFoxy_Hug:1220761726526423070>"
    commonmonkeydance = "<a:CommonMonkeyDance:1221032100631937084>"
    goldenmonkeydancereal = "<a:GoldenMonkeyDanceReal:1221032119954964560>"
    legendarymonkeydance = "<a:LegendaryMonkeyDance:1221032138795651092>"
    raremonkeydance = "<a:RareMonkeyDance:1221032156348940419>"
    shinymonkeydance = "<a:ShinyMonkeyDance:1221032176670212116>"
    uncommonmonkeydance = "<a:UncommonMonkeyDance:1221032194919628841>"
    bunnymoneyyy = "<a:bunnymoneyyy:1222290856363429999>"
    emolga_uwu = "<:emolga_uwu:1222401340609658890>"
    shayminsip = "<a:ShayminSip:1222865069780500550>"
    slowpokepensante = "<:Slowpokepensante:1230681805221396531>"
    super_incubator = "<:super_incubator:1232915732581322842>"
    pikathink = "<:pikaThink:1232915737086136330>"
    espurr_derp = "<:espurr_derp:1232916261881643019>"
    treecko_zz = "<a:treecko_zz:1232916280802279504>"
    sylveon_derp2 = "<:sylveon_derp2:1233387331864494092>"
    sylveon_pat = "<:sylveon_pat:1233387752914157588>"
    sylveon_think = "<:sylveon_think:1233387757896994867>"
    jigglypuff_derp = "<:jigglypuff_derp:1234307304988606485>"
    sylveon_heart = "<:sylveon_heart:1235836804759031819>"
    mimikyuheart = "<a:MimikyuHeart:1245523554909552660>"
    zorothumbs = "<:ZoroThumbs:1250305072513159269>"
    dedenne_heart = "<:dedenne_heart:1278372733474046054>"
    elissmile = "<:elisSmile:1279123323690942505>"
    eliscaught = "<:elisCaught:1279882105911906379>"
    elisnono = "<a:elisNONO:1280759900976447552>"
    elisignore = "<:elisIgnore:1280760104437813290>"
    elisshrug = "<:elisShrug:1280760109877956651>"
    elissip = "<:elisSip:1280760115384815668>"
    elisclap = "<a:elisClap:1280760120145346635>"
    kierzz = "<:kierzz:1280856457348124682>"
    smoliv_heart = "<:smoliv_heart:1281164801069940736>"
    gardevoirheart = "<:gardevoirheart:1282820397506760739>"
    fidough_cookie = "<:fidough_cookie:1283739696618274846>"
    fidough_wow = "<a:fidough_wow:1283739703140679703>"
    _6_green_flowera = "<:6_green_flowera:1283739717741056031>"
    cutegreenleaf = "<a:cutegreenleaf:1283744777086570557>"
    green_hearts222 = "<a:green_hearts222:1283744836389961769>"
    pikalolipop = "<:PikaLolipop:1285029651412025437>"
    fidough_flour = "<:fidough_flour:1285445709881020417>"
    knife = "<:Knife:1285622595399581758>"
    bounsweet = "<a:bounsweet:1288634948529553409>"
    hattrem = "<:hattrem:1289784433376890913>"
    chillet = "<:chillet:1293319293358047282>"
    cuteghostie = "<a:cuteghostie:1294624294671880223>"
    patreon_token = "<:patreon_token:1296818113735819405>"
    spidermanrighton = "<a:spidermanrighton:1297509188297162855>"
    joltik_hype = "<a:Joltik_hype:1297509883536609312>"
    joltik = "<:joltik:1297514168945082381>"
    petthejoltiks = "<a:PetTheJoltiks:1297514176155226143>"
    spidermanok = "<:SpiderManOk:1297514198162608150>"
    spider_like = "<:spider_like:1297514274389885012>"
    zorothanks = "<:zorothanks:1297516079169536090>"
    joltikhmm = "<:Joltikhmm:1297516320870371381>"
    gigantamax = "<:gigantamax:1300483729806065708>"
    shinygigantamax = "<:shinygigantamax:1300794317643841608>"
    world_boss_spawned = "<:world_boss_spawned:1300794324887535656>"
    sadkip = "<a:SadKip:1301969288092979281>"
    fidcoins = "<:fidCoins:1307109003305680896>"
    momo = "<a:Momo:1307501048167923722>"
    mimu_sip = "<:mimu_sip:1308252876883361804>"
    woopercool = "<:WooperCool:1309957008962879529>"
    diamond = "<a:Diamond:1311246088178634752>"
    wooper_cry = "<:wooper_cry:1314187982936215602>"
    grrr = "<:grrr:1318453014364688427>"
    runrun = "<a:runrun:1318455320040833115>"
    oofboi = "<:oofboi:1319378978368127109>"
    goldenmega = "<:goldenmega:1320554329224253512>"
    pogcrazy = "<a:POGCRAZY:1326163188592541799>"
    beangotobed = "<a:BEANgotobed:1328474166797533215>"
    sitting_duck = "<a:sitting_duck:1328582877968863264>"
    catto = "<:catto:1329649264481140867>"
    poliwhirl_eyes = "<:poliwhirl_eyes:1330371583000317962>"
    sylveonletmein = "<a:SylveonLetMeIn:1332480067431039109>"
    paissa_leave = "<a:paissa_leave:1337389243571503204>"
    nyaissaarrive = "<a:nyaissaarrive:1337418374770327633>"
    paw_cookie = "<:paw_cookie:1339051373798363208>"
    kekgold = "<a:KEKGold:1341088062804987934>"
    kekrainbow = "<a:kekrainbow:1341088294686953605>"
    peepoblush = "<:peepoBlush:1350778716288192632>"
    peepositti = "<:Peepositti:1350778779676442625>"
    nom = "<a:NOM:1353210857714094120>"
    coquette = "<:coquette:1357521376109527140>"
    skaiapat = "<a:skaiapat:1357570614877225183>"
    doubt = "<:Doubt:1358277386277224501>"
    classic = "<a:Classic:1365860519281426542>"
    wynauttt = "<:Wynauttt:1372066377967599806>"
    nuh_nuh_uh = "<a:nuh_nuh_uh:1373949312731451453>"
    iara_spin = "<a:iara_spin:1374571840999129188>"
    nerd = "<:nerd:1375664455064621106>"
    smirk = "<:smirk:1377024538302218261>"
    luv = "<:luv:1378307594002890752>"
    ana = "<:ana:1380875363793506385>"
    hehechatting = "<a:heheChatting:1381923856993751093>"
    pepe_old = "<:pepe_old:1382941344498188288>"
    poor = "<:poor:1384487427531472906>"
    ditto_business = "<:Ditto_business:1387605962218803200>"
    ppdinkdonk = "<a:Ppdinkdonk:1388789295065595925>"
    huh = "<a:HUH:1393128356668637225>"
    capybarah = "<:capybarah:1394570692019748935>"
    kawaiisakurablossom = "<:kawaiiSakuraBlossom:1396485566895489166>"
    mew_plushie = "<a:mew_plushie:1400262290074370161>"
    peepolaptophappy = "<a:peepoLaptopHappy:1404064544292077620>"
    ricedog = "<:ricedog:1404422993551032490>"
